(maint) Bump PE version to latest (2015.2.2)
* Also fixing locations of paths now they've changed in 2015.2.2
* Change localhost references to hostname:
Whenever I tried installing with localhost, the install would always fail at the earliest stage:

```
Loaded plugins: amazon-id, rhui-lb, security
Cleaning repos: puppet-enterprise-installer
Cleaning up Everything
!! ERROR: Could not connect to the postgresql server using the pe-postgres user.
```

I changed it to use the $EXTERNAL_HOSTNAME and it was fine after that

* Removed master classification - Not sure why this was needed?
* Remove dead S3 code (moved to new link)
* pe_mcollective no longer exists:
It's been moved to main PE Modules as `puppet_enterprise::profile::mcollective::agent` profile, and is automatically added as part of the initial run.

If you don't remove it, you get the following error:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Could not find class ::pe_mcollective for foo.bar at /etc/puppetlabs/code/environments/production/manifests/site.pp:11:3 on node foo.bar
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```